print("Xin chao cong viet tu dong!")
print("Toi dang hoc git nang cao")
print("Toi dang add dong thu ba")
print("toi dang add dong thu tu")
print("them tinh nang thu nghiem moi")
print("ngay hom nay la ...")
print("Thu nghiem in date lan 2")
print("new-feature")